### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ebarnell** [mg14/CoxHD#1]
When trying to install this package I received this error message:

Warning message: package ‘mg14/CoxHD/CoxHD’ is not available (for R version 3.3.2)
ERROR: dependency ‘mg14’ is not available for package ‘CoxHD’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/CoxHD’
Error: Command failed (1)

What R version is required to install this package?

**Comment by mg14** [comment]
I think you need to install
   >devtools::install_github("mg14/mg14")

as well. Apologies, this was missing.
Have updated README.md
